/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Estructuras.NodeUsuario;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import proyecto2.App;

/**
 *@Description: interfaz para agregar usuarios
 * @author Reinaldo Reyes & Catalina Matheus 
 * @version: 12/11/2023
 */
public class AddUsers extends javax.swing.JFrame {

    App app = App.getInstance();
    String nuevoUsuario = null;
    String tipo = null;
    boolean existe = false;

    /**
     * Creates new form AddUsers
     */
    public AddUsers() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.limpiarList();
        this.agregarElementosLista();
        this.agregarUsuariosLista(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputUsername = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaUsuariosActuales = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        Imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(inputUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 280, 40));

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jButton1.setText("AGREGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 130, 40));

        jToggleButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jToggleButton1.setText("ATRÁS");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 120, -1));

        jScrollPane1.setViewportView(ListaUsuariosActuales);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 240, 240));

        jList1.setFont(new java.awt.Font("Helvetica Neue", 0, 15));
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 300, 80));

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/NuevoAgregarUsuario.jpg"))); // NOI18N
        getContentPane().add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jList1ValueChanged

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        this.setVisible(false); 
        VerAgregarUsuarios i = new VerAgregarUsuarios(); 
        i.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void inputUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUsernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      nuevoUsuario = inputUsername.getText(); 
      tipo = jList1.getSelectedValue(); 
        if (nuevoUsuario == null || tipo == null || nuevoUsuario.equals("") || nuevoUsuario.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe agregar el username y el tipo de usuario! Intente nuevamente"); 
        }else{
            NodeUsuario nuevo = new NodeUsuario(nuevoUsuario, tipo); 
            app.getLista().appendLast(nuevo);
            this.agregarUsuariosLista(); 
            JOptionPane.showMessageDialog(null, "El usuario fue agregado exitosamente!"); 
            
            // test del timer
           
            
            inputUsername.setText("");
            jList1.clearSelection();
            nuevoUsuario = null; 
            tipo = null; 
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    
    
    /**
     * @Descripcion: funcion que limpia los JList antes de desplegar la
     * información
     * @return
     * @author: Catalina Matheus
     * @version: 17/10/2023
     */
    public DefaultListModel limpiarList() {
        DefaultListModel modelo = new DefaultListModel();
        jList1.setModel(modelo);
        ListaUsuariosActuales.setModel(modelo); 
        return modelo;
    }

     /**
     * @Descripcion: funcion que coloca todos los usuarios que estan en el grafo
     * en la jList
     * @return
     * @author: Catalina Matheus
     * @version: 17/10/2023
     */
    public DefaultListModel agregarElementosLista() {
        DefaultListModel modelo = (DefaultListModel) jList1.getModel();
        String[] types = {"prioridad_alta", "prioridad_media", "prioridad_baja"};
         for (int i = 0; i < 3; i++) {
            modelo.addElement(types[i]);
        }

        return modelo;
    }
    public String[] getUserNames() {
        NodeUsuario aux = app.getLista().getpFirst();
        String[] Usernames = new String[app.getLista().getSize()];
        for (int i = 0; i < app.getLista().getSize(); i++) {
            Usernames[i] = aux.getNombreUsuario();
            aux = aux.getpNext();
        }
        return Usernames;
    }

     public DefaultListModel agregarUsuariosLista() {
       DefaultListModel modelo = new DefaultListModel();  
        NodeUsuario aux = app.getLista().getpFirst(); 
        while(aux != null) {
            modelo.addElement(aux.getNombreUsuario());
            aux = aux.getpNext();
        }
        ListaUsuariosActuales.setModel(modelo);
        return modelo; 
    }
    public boolean itExist(String[] nombres, String usuario) {
        boolean existe = false;
        for (int i = 0; i < nombres.length; i++) {
            if (nombres[i].equals(usuario)) {
                existe = true;
            }
        }
        return existe;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagen;
    private javax.swing.JList<String> ListaUsuariosActuales;
    private javax.swing.JTextField inputUsername;
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
