/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Estructuras.NodeDocumento;
import Estructuras.NodeMonticulo;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import proyecto2.App;

/**
 *
 * @author reina
 */
public class LiberarCola extends javax.swing.JFrame {

    App app = App.getInstance();
    int eliminados = 0;

    /**
     * Creates new form LiberarCola
     */
    public LiberarCola() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.Eliminadosn.setText("0");
        this.limpiarListD();
        this.Eliminadosn.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ListImpresos = new javax.swing.JList<>();
        Imprimir = new javax.swing.JToggleButton();
        ImprimirAll = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        Eliminadosn = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        Imagen = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane4.setViewportView(ListImpresos);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 520, 210));

        Imprimir.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        Imprimir.setText("Imprimir Seleccion");
        Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimirActionPerformed(evt);
            }
        });
        jPanel1.add(Imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 160, 20));

        ImprimirAll.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        ImprimirAll.setText("Imprimir todo");
        ImprimirAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimirAllActionPerformed(evt);
            }
        });
        jPanel1.add(ImprimirAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 120, 20));

        jToggleButton4.setText("-");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, 50, 30));

        jToggleButton5.setText("+");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 50, 30));

        Eliminadosn.setEditable(false);
        Eliminadosn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminadosnActionPerformed(evt);
            }
        });
        jPanel1.add(Eliminadosn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 40, 30));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel10.setText("OPCIONES PARA IMPRIMIR");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 240, -1));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel11.setText("DOCUMENTOS IMPRESOS");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 240, -1));

        jToggleButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jToggleButton1.setText("ATRÁS");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImprimirCola.jpg"))); // NOI18N
        jPanel1.add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        jToggleButton2.setText("+");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 50, 30));

        jToggleButton3.setText("-");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 50, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        this.setVisible(false);
        SistemaOperativo a = new SistemaOperativo();
        a.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void ImprimirAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirAllActionPerformed
        int tamano = app.getbMonticulo().getSize();
        NodeMonticulo eliminado = app.getbMonticulo().eliminar_min();
        if (eliminado != null) {

            NodeMonticulo[] listaEliminados = new NodeMonticulo[tamano];
            for (int i = 0; i < tamano; i++) {
                listaEliminados[i] = eliminado;
                eliminado = app.getbMonticulo().eliminar_min();
            }
            this.desplegarDocumentos(listaEliminados);
            this.sacarCola(listaEliminados);
        } else {
            JOptionPane.showMessageDialog(null, "No hay documentos en la cola de impresion");
        }


    }//GEN-LAST:event_ImprimirAllActionPerformed

    private void ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirActionPerformed
        // TODO add your handling code here:
        eliminados = Integer.parseInt(this.Eliminadosn.getText());
        if (eliminados != 0) {

            NodeMonticulo eliminado = app.getbMonticulo().eliminar_min();
            if (eliminado != null) {
                app.getbMonticulo().insertar(eliminado);
                NodeMonticulo[] listaEliminados = new NodeMonticulo[eliminados];
                for (int i = 0; i < eliminados; i++) {

                    eliminado = app.getbMonticulo().eliminar_min();
                    listaEliminados[i] = eliminado;
                }
                this.desplegarDocumentos(listaEliminados);
                this.Eliminadosn.setText("0");
                this.sacarCola(listaEliminados);
            } else {
                JOptionPane.showMessageDialog(null, "No hay documentos en la cola de impresion");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Tiene que seleccionar una cantidad de documentos para imprimir");
        }

    }//GEN-LAST:event_ImprimirActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        String num = Eliminadosn.getText();
        int numInt = Integer.parseInt(num);
        this.Eliminadosn.setText(Integer.toString(numInt + 1));
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        String num = this.Eliminadosn.getText();
        int numInt = Integer.parseInt(num);
        if (numInt != 1) {
            this.Eliminadosn.setText(Integer.toString(numInt - 1));
        }
    }//GEN-LAST:event_jToggleButton3ActionPerformed
    /**
     * @Descripcion: Despliega los documentos eliminados en el Jlist
     * @param lista
     * @return
     * @version: 17/11/2023
     * @author: Reinaldo Reyes
     */
    public void desplegarDocumentos(NodeMonticulo[] lista) {
        DefaultListModel modelo = new DefaultListModel();
        String info;
        for (int i = 0; i < lista.length; i++) {
            NodeDocumento datos = lista[i].getData();
            info = "Nombre: " + datos.getNombre() + "    Tipo:" + datos.getTipo() + "   Tamaño:" + datos.getTamano();

            modelo.addElement(info);
        }

        this.ListImpresos.setModel(modelo);
    }


    /**
     * @Descripcion: Cambia el valor de verdad de los documentos, 
     * que ya no estan en la cola de impresion
     * @param lista
     * @return 
     * @version: 17/11/2023
     * @author: Reinaldo Reyes
     */
    public void sacarCola(NodeMonticulo[] lista){
        for (int i = 0; i < lista.length; i++) {
            lista[i].getData().setEnCola(false);
            app.getHashTable().EliminateDoc(lista[i]);
        }
    }

    /**
     * @Descripcion: funcion que limpia los JList antes de desplegar la
     * información
     * @return
     * @author: Catalina Matheus
     * @version: 17/10/2023
     */
    public DefaultListModel limpiarListD() {
        DefaultListModel modelo = new DefaultListModel();
        ListImpresos.setModel(modelo);
        return modelo;
    }


    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        String num = Eliminadosn.getText();
        int numInt = Integer.parseInt(num);
        if (numInt != 0) {
            this.Eliminadosn.setText(Integer.toString(numInt - 1));
        }
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed

        String num = Eliminadosn.getText();
        int numInt = Integer.parseInt(num);
        if (numInt < app.getbMonticulo().getSize()) {
            this.Eliminadosn.setText(Integer.toString(numInt + 1));
        }


    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void EliminadosnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminadosnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminadosnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LiberarCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LiberarCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LiberarCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LiberarCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LiberarCola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Eliminadosn;
    private javax.swing.JLabel Imagen;
    private javax.swing.JToggleButton Imprimir;
    private javax.swing.JToggleButton ImprimirAll;
    private javax.swing.JList<String> ListImpresos;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    // End of variables declaration//GEN-END:variables
}
