/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import javax.swing.JOptionPane;
import proyecto2.App;

/**
 *@Description interfaz principal de la simulación 
 * @author Catalina Matheus
 * @version 12/11/2023
 */
public class MainInterface extends javax.swing.JFrame {
    App app = App.getInstance(); 
    /**
     * Creates new form MainInterface
     */
    public MainInterface() {
        initComponents();
        transpareciaButton(); 
        this.setLocationRelativeTo(null); 
        this.setVisible(true); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgregarUsuarios = new javax.swing.JToggleButton();
        CargarArchivoCSV = new javax.swing.JToggleButton();
        EliminarUsuarios = new javax.swing.JToggleButton();
        CrearDoc = new javax.swing.JToggleButton();
        SistemaOperativo = new javax.swing.JToggleButton();
        imprimirDoc = new javax.swing.JToggleButton();
        Imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AgregarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 360, 60));

        CargarArchivoCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarArchivoCSVActionPerformed(evt);
            }
        });
        getContentPane().add(CargarArchivoCSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, 300, 90));

        EliminarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(EliminarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 280, 80));

        CrearDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearDocActionPerformed(evt);
            }
        });
        getContentPane().add(CrearDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 300, 100));

        SistemaOperativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SistemaOperativoActionPerformed(evt);
            }
        });
        getContentPane().add(SistemaOperativo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 520, 310, 60));

        imprimirDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirDocActionPerformed(evt);
            }
        });
        getContentPane().add(imprimirDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 430, 350, 80));

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevaPinical.jpg"))); // NOI18N
        getContentPane().add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarUsuariosActionPerformed
        this.setVisible(false); 
        VerAgregarUsuarios i = new VerAgregarUsuarios(); 
        i.setVisible(true);
//        AddUsers aU = new AddUsers(); 
//        aU.setVisible(true);
        
    }//GEN-LAST:event_AgregarUsuariosActionPerformed

    private void CargarArchivoCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarArchivoCSVActionPerformed
        this.setVisible(false); 
        CargarArchivo cA= new CargarArchivo(); 
        cA.setVisible(true);
    }//GEN-LAST:event_CargarArchivoCSVActionPerformed

    private void EliminarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUsuariosActionPerformed
        this.setVisible(false); 
        EliminarUsuario e = new EliminarUsuario(); 
        e.setVisible(true);
    }//GEN-LAST:event_EliminarUsuariosActionPerformed

    private void CrearDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearDocActionPerformed
        this.setVisible(false); 
        CrearEliminarDoc i = new CrearEliminarDoc(); 
        i.setVisible(true); 
    }//GEN-LAST:event_CrearDocActionPerformed

    private void SistemaOperativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SistemaOperativoActionPerformed
        this.setVisible(false); 
        SistemaOperativo i = new SistemaOperativo(); 
        i.setVisible(true); 
    }//GEN-LAST:event_SistemaOperativoActionPerformed

    private void imprimirDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirDocActionPerformed
        this.setVisible(false);
        AgregarCola a = new AgregarCola();
        a.setVisible(true);
        
    }//GEN-LAST:event_imprimirDocActionPerformed
     /**
     * @Description: método que hace que todos los botones de la interfaz sean transparentes 
     * @author: Catalina Matheus 
     * @version: 12/11/2023
     */
   public void transpareciaButton(){
       EliminarUsuarios.setOpaque(false);
       EliminarUsuarios.setContentAreaFilled(false);
       EliminarUsuarios.setBorderPainted(false); 
       
       AgregarUsuarios.setOpaque(false);
       AgregarUsuarios.setContentAreaFilled(false);
       AgregarUsuarios.setBorderPainted(false); 
       
       CargarArchivoCSV.setOpaque(false);
       CargarArchivoCSV.setContentAreaFilled(false);
       CargarArchivoCSV.setBorderPainted(false); 
       
       
       CrearDoc.setOpaque(false);
       CrearDoc.setContentAreaFilled(false);
       CrearDoc.setBorderPainted(false); 
       
       SistemaOperativo.setOpaque(false);
       SistemaOperativo.setContentAreaFilled(false);
       SistemaOperativo.setBorderPainted(false); 
       
       imprimirDoc.setOpaque(false);
       imprimirDoc.setContentAreaFilled(false);
       imprimirDoc.setBorderPainted(false); 
       
   } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton AgregarUsuarios;
    private javax.swing.JToggleButton CargarArchivoCSV;
    private javax.swing.JToggleButton CrearDoc;
    private javax.swing.JToggleButton EliminarUsuarios;
    private javax.swing.JLabel Imagen;
    private javax.swing.JToggleButton SistemaOperativo;
    private javax.swing.JToggleButton imprimirDoc;
    // End of variables declaration//GEN-END:variables
}
