/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Estructuras.NodeMonticulo;
import javax.swing.JOptionPane;
import proyecto2.App;

/**
 * @Description interfaz para mostrar las funcionalidades del SO en la
 * simulación
 * @author Catalina Matheus
 * @version 12/11/2023
 */
public class SistemaOperativo extends javax.swing.JFrame {

    App app = App.getInstance();

    /**
     * Creates new form SistemaOperativo
     */
    public SistemaOperativo() {
        initComponents();
        transpareciaButton();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        Liberar = new javax.swing.JToggleButton();
        Eliminar = new javax.swing.JToggleButton();
        Ver = new javax.swing.JToggleButton();
        Imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jToggleButton1.setText("ATRÁS");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 130, -1));

        Liberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LiberarActionPerformed(evt);
            }
        });
        getContentPane().add(Liberar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 430, 50));

        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 610, 60));

        Ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerActionPerformed(evt);
            }
        });
        getContentPane().add(Ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 280, 50));

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/NewSO.jpg"))); // NOI18N
        getContentPane().add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        this.setVisible(false);
        MainInterface i = new MainInterface();
        i.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void LiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LiberarActionPerformed
        // TODO add your handling code here:

        this.setVisible(false);
        LiberarCola a = new LiberarCola();
        a.setVisible(true);

    }//GEN-LAST:event_LiberarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        NodeMonticulo muestra = app.getbMonticulo().peek();
        if (muestra == null) {

            JOptionPane.showMessageDialog(null, "Todavia no hay documentos en la cola de impresión!");
        } else {
            this.setVisible(false);
            EliminarColaSO o = new EliminarColaSO();
            o.setVisible(true);
        }


    }//GEN-LAST:event_EliminarActionPerformed

    private void VerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerActionPerformed
        NodeMonticulo muestra = app.getbMonticulo().peek();
        if (muestra == null) {

            JOptionPane.showMessageDialog(null, "Todavía no hay documentos en la cola de impresión!");
        } else {
            this.setVisible(false);
            VerCola i = new VerCola();
            i.setVisible(true);
        }

    }//GEN-LAST:event_VerActionPerformed
    /**
     * @Description: método que hace que todos los botones de la interfaz sean
     * transparentes
     * @author: Catalina Matheus
     * @version: 12/11/2023
     */
    public void transpareciaButton() {
        Eliminar.setOpaque(false);
        Eliminar.setContentAreaFilled(false);
        Eliminar.setBorderPainted(false);

        Liberar.setOpaque(false);
        Liberar.setContentAreaFilled(false);
        Liberar.setBorderPainted(false);

        Liberar.setOpaque(false);
        Liberar.setContentAreaFilled(false);
        Liberar.setBorderPainted(false);

        Ver.setOpaque(false);
        Ver.setContentAreaFilled(false);
        Ver.setBorderPainted(false);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaOperativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaOperativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaOperativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaOperativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaOperativo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Eliminar;
    private javax.swing.JLabel Imagen;
    private javax.swing.JToggleButton Liberar;
    private javax.swing.JToggleButton Ver;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
