/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import javax.swing.JOptionPane;
import proyecto2.App;

/**
 *
 * @author Catalina Matheus
 */
public class VerCola extends javax.swing.JFrame {
    App app = App.getInstance(); 

    /**
     * Creates new form VerCola
     */
    public VerCola() {
        initComponents();
        this.setVisible(true); 
        this.setLocationRelativeTo(null);
        this.transpareciaButton(); 
        this.mostrarCola.setText(app.getbMonticulo().imprimirCola());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        arbol = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mostrarCola = new javax.swing.JTextArea();
        imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jToggleButton1.setText("ATRÁS");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 100, -1));

        arbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arbolActionPerformed(evt);
            }
        });
        getContentPane().add(arbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 210, 80));

        mostrarCola.setColumns(20);
        mostrarCola.setRows(5);
        jScrollPane1.setViewportView(mostrarCola);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 740, 70));

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ColaI.jpg"))); // NOI18N
        getContentPane().add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        this.setVisible(false); 
        SistemaOperativo so = new SistemaOperativo(); 
        
        so.setVisible(true); 
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void arbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arbolActionPerformed
         if(app.getbMonticulo().isEmpty()){
           JOptionPane.showMessageDialog(null, "No se puede mostrar el arbol porque está vacío!"); 
           
       }else{
             System.out.println(app.getbMonticulo().getSize());
           GUI gui = new GUI(app.getbMonticulo()); 
       }
    }//GEN-LAST:event_arbolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerCola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerCola().setVisible(true);
            }
        });
    }

     /**
     * @Description: método que hace que todos los botones de la interfaz sean transparentes 
     * @author: Catalina Matheus 
     * @version: 12/11/2023
     */
    public void transpareciaButton(){
       arbol.setOpaque(false);
       arbol.setContentAreaFilled(false);
       arbol.setBorderPainted(false); 
       
       
       
   } 
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton arbol;
    private javax.swing.JLabel imagen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextArea mostrarCola;
    // End of variables declaration//GEN-END:variables
}
